services:

  mysql:
    image: mysql:8.0
    container_name: hackhub-mysql
    restart: unless-stopped

    env_file:
      - .env

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    volumes:
      - hackhub_mysql_data:/var/lib/mysql

  backend:
    build: ./hackhub-backend
    container_name: hackhub-backend
    restart: unless-stopped

    depends_on:
      - mysql

    environment:
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: "8081"
      APP_JWT_SECRET: ${APP_JWT_SECRET}
      APP_JWT_EXPIRATION_MS: ${APP_JWT_EXPIRATION_MS}

    expose:
      - "8081"

  frontend:
    build:
      context: ./hackhub-frontend
      dockerfile: Dockerfile.prod

    container_name: hackhub-frontend
    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "80:80"

volumes:
  hackhub_mysql_data: